CREATE TABLE EMPLOYEES (
  employee_id INT AUTO_INCREMENT  PRIMARY KEY,
  first_name VARCHAR(250) NOT NULL,
  pesel VARCHAR(250) NOT NULL,
  department_id INT NOT NULL
);

CREATE SEQUENCE HIBERNATE_SEQUENCE START WITH 4 INCREMENT BY 1;
